name: adobe_deactivation_bypass
description: A CLI tool to bypass Adobe's deactivation prompt.
version: 1.0.0
repository: https://github.com/YarosMallorca/adobe_deactivation_bypass

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
